import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import RegisterModel from './components/modals/RegisterModal'
import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/modals/RegisterModal'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RegisterModel />
        <ClientOnly>
         <RegisterModal/>
        <Navbar/>  
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
